[[headers]]
  for = "/*"
  [headers.values]
    # Protects against XSS attacks
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    # Basic Content Security Policy
    Content-Security-Policy = "default-src 'self';"
