[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    # Updated to allow external styles from Medium
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://glyph.medium.com; img-src 'self' data: https://images.unsplash.com https://i.pinimg.com https://medium.com;"
